

version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4


  install_awscli:
    description: Install AWS CLI v2
    steps:
      - run:
          name: Install AWS CLI v2
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
 
jobs:
 
## DEPLOY INFRASTRUCTURE
  terraform-initial:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform init
          command: |
            cd terraform
            terraform init -input=false
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-planning:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform plan
          command: |
            cd terraform
            terraform plan -out tfapply 
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-applying:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform apply
          command: |
            cd terraform
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .
      
  terraform-stop:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            cd terraform
            terraform plan -destroy -out tfdestroy 
          when: on_fail
      - persist_to_workspace:
          root: .
          paths:
            - .
   

  terraform-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            cd terraform
            terraform destroy -auto-approve tfdestroy

  build-blog-app_web-app:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
        # installs a docker client that will be used to run the docker commands
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            cd blog-app  
            docker build -t blog-app-app .
      - run:
          name: Push to Docker Hub
          command: |
            cd django_project
            echo "$DOCKER_PASSWORD"
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag $APP:latest $DOCKER_USERNAME/$APPLICATION
            docker push $DOCKER_USERNAME/$APPLICATION
            
  deploy-blog-app_web-app:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - install_awscli
      - run:
          name: Install kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Configure kubectl
          command: |
            aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - run:
          name: Deploy Docker image to EKS cluster
          command: |
            sed -i "s|IMAGE|$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_USERNAME/$APPLICATION:latest|g" kubernetes_cluster/*yaml
            kubectl apply -f kubernetes_cluster/
            kubectl get pods
            kubectl get services
            
  deploy-sock-shop:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - install_awscli
      - run:
          name: Install kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Configure kubectl
          command: |
            aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - run:
          name: Deploy Docker image to EKS cluster
          command: |
            sed -i "s|IMAGE|$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_USERNAME/$APPLICATION:latest|g" manifest/*yaml
            kubectl create namespace sock-shop
            kubectl apply -f kubernetes/
            kubectl get services namespace=sock-shop
            
  deploy-prometheus:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - install_awscli
      - run:
          name: Install kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Configure kubectl
          command: |
            aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - run:
          name: Deploy Docker image to EKS cluster
          command: |
            sed -i "s|IMAGE|$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_USERNAME/$APPLICATION:latest|g" kubernetes/manifests-monitoring/*yaml
            kubectl apply -f kubernetes/manifests-monitoring/
            
workflows:
  version: 2
  blog-app_web-deployment:
    jobs:
       - terraform-initial
       - terraform-planning:
           requires: ["terraform-initial"]
       - hold-applying:
           type: approval
           requires: ["terraform-planning"]
       - terraform-applying:
           requires: ["hold-applying"]
       - terraform-stop:
           requires: ["terraform-applying"]
       - hold-destroy:
           type: approval
           requires: ["terraform-stop"]
       - terraform-destroy:
           requires: ["hold-destroy"]  
       - build-blog-app_web-app:
            requires: ["terraform-applying"]
      # - deploy-blog-app_web-app:
       #    requires: ["terraform-applying, build-blog-app_web-app"]
       #- deploy-sock-shop:
        #   requires: ["terraform-applying, build-blog-app_web-app"]
       #- deploy-prometheus:
        #   requires: ["terraform-applying, build-blog-app_web-app"]
